### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by Abhijit25Mishra** [iiitkottayam/Enlace#1]
- Add more emojis, make it more welcoming for the boss contributors.
- fix typos
- Add additonal resources if required.

**Comment by Biswadeepgiri** [comment]
hi i am interested
Please convey me further details.
Name-Biswadeep Giri
Roll Number-2021BCS0151
Email-biswadeep21bcs151@iiitkottayam.ac.in

**Comment by Abhijit25Mishra** [comment]
Let me know by when u can get the work done. 

There are 2 markdown file one on the main page when u open the repo ->  this contains the details of the enlace project. this should be inviting in nature. 

the other when u click on the enlace-main folder , this should give u the details of the of the tech stack used and other nessary stuff. 

Visit other popular repos and get more info how they organize there readmefiles
