### ISSUE TITLE
Contacts page

### ISSUE THREAD

**Issue by Abhijit25Mishra** [iiitkottayam/Enlace#5]
- This page will be accessed from the navbar from the main page. (apply proper links)
- [Example][https://brandaffair.ro/contact] of contact page. this is one of the best, u dont need to implement the starting animation or the map feature.
- make the basic layout similar or have a look at our design present in the discord channel.
- components like navbar ,etc are already built use them with proper styling.

**Comment by freak-10** [comment]
I am working on this
